server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/shopmart_inventory?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  # Câu 4: Distributed Cache với Redis (Cache-Aside)
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms
  cache:
    type: redis
    redis:
      time-to-live: 60000ms
      cache-null-values: false
  kafka:
    consumer:
      group-id: inventory-service-group
      properties:
        spring.json.value.default.type: com.shopmart.inventory.event.OrderEvent

logging:
  level:
    com.shopmart.inventory: INFO
